#name: Docker Image CI
#
#on:
#  push:
#    branches:
#      - master
#    paths-ignore:
#      - 'README.md'
#
#env:
#  IMAGE_NAME: sui2
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build
#        uses: docker/build-push-action@v2
#        with:
#          file: ./Dockerfile
#          platforms: linux/amd64
#          push: true
#          tags: |
#            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
